### PR TITLE
Pause patch

### PR DESCRIPTION
**Pull request by ewnd9**
On pause audio stop playing with ~1 sec delay, resume works immediately. 
Also please keep in mind like in previous pull request I didn't include rebuilded dists, so you need to do it before publishing new version on npm

### CODE REVIEW

**Comment by guo-yu** [comment]
Sure, thank you so much

**Comment by ewnd9** [comment]
:tada:

**Comment by kingdido999** [comment]
@ewnd9 Hi, I'm experiencing a 1~2 secs delay on `pause()` and `stop()` when playing from url with stream enabled. I noticed that both methods are calling:

```javascript
this.speaker.Speaker.end()
```

which means it's an issue with [node-speaker](https://github.com/TooTallNate/node-speaker)? Is there any room for speed improvement? Thank you.

**Comment by ewnd9** [comment]
@kingdido999  Yep, I suppose it's related to https://github.com/TooTallNate/node-speaker/issues/13

**Comment by kingdido999** [comment]
@ewnd9 Thanks, I'll look into them.

**Pull request merged**
